### ISSUE TITLE
Create notification messages regarding wearing time

### ISSUE THREAD

**Issue by RiLights** [RiLights/aligntime#21]
@OlenkaP Would be nice to understand when and what exactly we have to notify.

**Comment by OlenkaP** [comment]
@RiLights Have attached document, that outlines my understanding of "Reminders" functionality. Happy to answer any questions :)
[AlignTime reminders.docx](https://github.com/RiLights/aligntime/files/4001828/AlignTime.reminders.docx)

**Comment by RiLights** [comment]
Hey @OlenkaP,

Can you please expand .docx file because looks like it is not working properly everywhere?

**Comment by OlenkaP** [comment]
@RiLights sorry :( should be working now?

When user clicks ‘Pause’ on Today screen I would expect little pop up window, that would allow to select reminder time and also would have default reminder times too.
This is manual reminder picker. Range from 0 hours 5 minutes to 23 hours 55 minutes, using 5 minute intervals. Default should be set to 0 hours 30 minutes

_Remind me to wear aligners again in…._
![image](https://user-images.githubusercontent.com/52235757/71469074-f312f780-282c-11ea-9860-69fba003c240.png)
Standard options should include:

15 minutes | 30 minutes | 45 minutes | 1 hour
-- | -- | -- | --


Then Users should be able to select options:

Cancel | No Reminder | Confirm
-- | -- | --



**Cancel** = Cancels action of ‘Pausing’ wear time. Takes user back to the ‘Today’ screen, where ‘Pause’ still will be available for them.

![image](https://user-images.githubusercontent.com/52235757/71469170-2eadc180-282d-11ea-8de4-784c562e36df.png)
**No Reminder** = Wear time is now paused and User is taken back to ‘Today’ screen, where, button ‘Play’ will appear. (So that User can hit ‘Play’, when they are wearing Aligners again). User doesn’t receive any reminders.
![image](https://user-images.githubusercontent.com/52235757/71469220-47b67280-282d-11ea-9aac-742c1cb24f88.png)
**Confirm** = Wear time is now paused and User is taken back to ‘Today’ screen, where, button ‘Play’ will appear. (So that User can hit ‘Play’, when they are wearing Aligners again). User would receive reminder in the time interval they’ve selected (i.e. 30 min).

Reminder message 1 would say: _Time to put your aligners on again._

If user doesn’t navigate to the AlignTime and clicks ‘Play’, they receive two more reminders: one in 2 minutes from original reminder value (i.e. in 32 minutes time) and one more in 5 minutes from then (i.e. 37 minutes time). 

Reminder message 2 would say: _Don’t forget to put your aligners on._

Reminder 3 would say: _Your aligners have been out for a while now. It’s time to put them back on._

Pop Up window would look something of this kind
![image](https://user-images.githubusercontent.com/52235757/71469239-5ef56000-282d-11ea-9ee9-6e4f594eecdc.png)

**Comment by RiLights** [comment]
Looks really cool! 
Probably, your description is interferencing with other tasks.

**Comment by RiLights** [comment]
Link notes regarding notifications:
https://developer.apple.com/videos/play/wwdc2016/707
https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refresh

**Comment by RiLights** [comment]
Hey @OlenkaP 
Do we have some reminders which are related to wear time? Like: "You are wearing aligners too long"

**Comment by OlenkaP** [comment]
@RiLights no, I don't think this would be necessary as the goal is to be wearing aligners for as many hours as possible

**Comment by RiLights** [comment]
Ready to test but right now it is in the light/debug version:
![IMG_0697_](https://user-images.githubusercontent.com/11796006/71759818-05212400-2f18-11ea-8217-bea2f5a76a61.jpg)
Also it works even if application removed from the memory.

**Comment by OlenkaP** [comment]
@RiLights i love it!!! so cool

**Comment by OlenkaP** [comment]
Can’t be too long :)
